language: php

dist: xenial

services:
    - mysql
    - postgresql
    - redis

php:
    - 8.0

before_script:
    - travis_retry composer update
    - psql -c 'create database tests;' -U postgres
    - mysql -e 'CREATE DATABASE tests;'

script:
    - vendor/bin/phpunit --configuration=phpunit.pgsql.xml
    - vendor/bin/phpunit --configuration=phpunit.mysql.xml
    - vendor/bin/phpunit