language: php

dist: xenial

services:
    - postgresql
    - redis

php:
    - 8.0

before_script:
    - travis_retry composer update
    - psql -c 'create database tests;' -U postgres

script:
    - vendor/bin/phpunit --configuration=phpunit.pgsql.xml