# For more information: https://laravel.com/docs/sail
version: '3'
services:
  advanced-nested-set-pgsql:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: 'tests'
      POSTGRES_DB: 'tests'
      POSTGRES_USER: 'tests'
      POSTGRES_PASSWORD: 'tests'
    volumes:
      - 'advanced-nested-set-pgsql:/var/lib/postgresql/data'
    networks:
      - advanced-nested-set
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
  advanced-nested-set-mysql:
    image: 'mysql/mysql-server:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'tests'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'tests'
      MYSQL_USER: 'tests'
      MYSQL_PASSWORD: 'tests'
    volumes:
      - 'advanced-nested-set-mysql:/var/lib/mysql'
    networks:
      - advanced-nested-set
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ptests"]
      retries: 3
      timeout: 5s
  advanced-nested-set-sqlsrv:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=P@ssword
      - ACCEPT_EULA=Y
      - SA_DATABASE=tests
      - SA_USER=SA
    volumes:
      - 'advanced-nested-set-sqlsrv:/var/opt/mssql'
    ports:
      - "1433:1433"
    networks:
      - advanced-nested-set
networks:
  advanced-nested-set:
    driver: bridge
volumes:
  advanced-nested-set-pgsql:
    driver: local
  advanced-nested-set-mysql:
    driver: local
  advanced-nested-set-sqlsrv:
    driver: local